### ISSUE TITLE
Update Mosquitto to 2.0

### ISSUE THREAD

**Issue by marcolew** [shantanoo-desai/tiguitto#33]
Using the new Mosquitto 2.0 version should solve our issues with user mangement and topic registration as Mosquitto 2.0 also includes a management dashboard

**Comment by shantanoo-desai** [comment]
We can create a different repository or branch that can use:

1. Mosquitto 2.0
2. InfluxDB 2.0
3. Telegraf v1.16/v1.17
4. Grafana (optional) since InfluxDB 2.0 provides a lot of end user features.

**Comment by marcolew** [comment]
Good idea, just started a new repository from scratch: https://github.com/iotstack-co/iotstack
I thought we can focus on the "Letsencrypt" version as maintaining all three scripts is a bit challenging. I hope you will contribute to this. ;-)

Our joint projects however focus on cloud installation. I already experimented with Mosquitto 2.0 and Admin-Board using Docker-Compose to set it up. This is very promissing, I will soon commit the first version.
