### ISSUE TITLE
Prototype MQTT Mosquito Connection not working

### ISSUE THREAD

**Issue by dualizeo** [shantanoo-desai/tiguitto#34]
Hi, I am attempted to connect to mosquitto broker but since MQTTFX is no longer free, I've been trying to use MQTT Explorer, MQTTBOX, MQTTLens, EMQX Client ( MQTTX ) with no luck connecting to mosquitto, any help is appreciated. 

( I will test selfsigned now, then move on to Lety's Encrypt )
self signed could not complete as error states: IP does not match certificate's altenames: IP: 192.168.10.25 is not in the cert's list:
I edited the generate-certs.sh with the following:
`CN=$(192.168.10.25 -I `

Certbot folder is missing 
```
00-install-certbot.sh
01-generate-certs.sh
```
🤔

**Comment by shantanoo-desai** [comment]
@dualizeo Thanks for reporting this. Let me get back to you on this once I do some local tests and see if I can reproduce it

**Comment by shantanoo-desai** [comment]
@dualizeo you are right, the script files were deleted, I have reintroduced the scripts in `certbot` directory

**Comment by shantanoo-desai** [comment]
Also I am not sure why you would do `CN=$(192.168.10.25 -I)`. The actual way would be to just set `CN=192.168.10.25`

**Comment by dualizeo** [comment]
> Also I am not sure why you would do `CN=$(192.168.10.25 -I)`. The actual way would be to just set `CN=192.168.10.25`

Thank you for adding the scripts, I will test out Certbot soon, however I did managed to get self signed certificates working using MQTTX client :) and based on that CN code I was looking at the following:
https://github.com/InfluxCommunity/tiguitto/tree/master/selfsigned/generate-certs.sh
```
# Use IP Address for CN
CN=$(hostname -I | awk '{print $1}')
```
so Instead I will try CN=My IP 
as you mentioned, or I will replace it with a local dns record created in my router.
Thank you !

**Comment by shantanoo-desai** [comment]
@dualizeo I am closing this issue. If you have similar problems please reopen this issue
